#!/usr/bin/env sh

# Optional prepare-commit-msg hook for customizing commit messages
# You can remove this file if not using it

# If using Commitizen
if [ -z "${2-}" ]; then
  exec < /dev/tty && node_modules/.bin/cz --hook || true
fi
